name = "natiq-masthul"
compatibility_date = "2023-10-01"

[env.production]
account_id = "YOUR_ACCOUNT_ID"
zone_id = "YOUR_ZONE_ID"
route = "natiq.yourdomain.com/*"

[site]
bucket = "./frontend"
entry-point = "./backend"

build.command = "npm run build"
build.upload.format = "service-worker"
